services:
  api-php:
    build:
      target: app
    volumes:
      - ./api/.docker/php/php.ini:/usr/local/etc/php/conf.d/ba-event.ini:ro
    environment:
      APP_ENV: production
      APP_DEBUG: "false"

  api-queue:
    build:
      target: app

  web:
    build:
      target: runner
    volumes: []
    environment:
      NODE_ENV: production
